### ISSUE TITLE
schedule_update_ha_state errors

### ISSUE THREAD

**Issue by nantostars** [SwiCago/HeatPump#100]
Hello,
I'm using this fantastic project to control my mitsubishi units with HomeAssistant and everything works fine, but I have some errors logged by HomeAssistant.

`2019-01-22 10:41:11 ERROR (MainThread) [homeassistant.core] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/climate/mitsubishi_mqtt.py", line 107, in message_received
    self.schedule_update_ha_state()
  File "/opt/homeassistant/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 317, in schedule_update_ha_state
    self.hass.add_job(self.async_update_ha_state(force_refresh))
AttributeError: 'NoneType' object has no attribute 'add_job'`

NOTE: I also changed line 188 of mitsubishi_mqtt.py from **self.update_ha_state()** to **self.schedule_update_ha_state()**

How to fix that error?

**Comment by SwiCago** [comment]
Please join the gitter chat and ask for help there. Home assistant errors have nothing to do with this library, so I can not help you resolve these errors.
