### ISSUE TITLE
set_temperature in mitsubishi_mqtt.py uses deprecated update_ha_state() method

### ISSUE THREAD

**Issue by shampeon** [SwiCago/HeatPump#106]
In the Home Assistant integration mitsubishi_mqtt.py, most of the methods have been updated to use schedule_update_hat_state, but set_temperature still uses the deprecated update_ha_state() method, which throws an error in HA 0.86.4:

`doing job: Task exception was never retrieved

Traceback (most recent call last):
  File "/home/homeassistant/.pyenv/versions/3.6.0/lib/python3.6/asyncio/tasks.py", line 181, in _step
    result = coro.throw(exc)
  File "/home/homeassistant/.pyenv/versions/3.6.0/envs/ha/lib/python3.6/site-packages/homeassistant/helpers/service.py", line 289, in _handle_service_platform_call
    await func(entity, data)
  File "/home/homeassistant/.pyenv/versions/3.6.0/envs/ha/lib/python3.6/site-packages/homeassistant/components/climate/__init__.py", line 574, in async_service_temperature_set
    await entity.async_set_temperature(**kwargs)
  File "/home/homeassistant/.pyenv/versions/3.6.0/lib/python3.6/asyncio/futures.py", line 331, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/home/homeassistant/.pyenv/versions/3.6.0/lib/python3.6/asyncio/tasks.py", line 244, in _wakeup
    future.result()
  File "/home/homeassistant/.pyenv/versions/3.6.0/lib/python3.6/asyncio/futures.py", line 244, in result
    raise self._exception
  File "/home/homeassistant/.pyenv/versions/3.6.0/lib/python3.6/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/homeassistant/config/custom_components/climate/mitsubishi_mqtt.py", line 188, in set_temperature
    self.update_ha_state()
AttributeError: 'MqttClimate' object has no attribute 'update_ha_state'
`

Change the method call to schedule_update_ha_state() to fix.

**Comment by shampeon** [comment]
#107 Created PR for this.
