### ISSUE TITLE
Home Assistant integration: Not work if heatpump on and restart home assistant

### ISSUE THREAD

**Issue by dzungpv** [SwiCago/HeatPump#114]
The Home Assistant integration work fine until i restart home assistant.
It not show anymore until i power cycle the heatpump.
When not word it show in HA logs:
```
Error doing job: Task exception was never retrieved

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 352, in _async_add_entity
    await entity.async_update_ha_state()
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 232, in async_update_ha_state
    state = self.state
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/climate/__init__.py", line 209, in state
    if self.current_operation:
  File "/config/custom_components/mitsubishi_mqtt/climate.py", line 170, in current_operation
    return me_to_ha[self._current_operation]
KeyError: None

```

**Comment by SwiCago** [comment]
Ask in the gitter chat for help. This has nothing to do with the library.
